### ISSUE TITLE
Strange effects around model instances destructors?

### ISSUE THREAD

**Issue by tnowotny** [tnowotny/stdpc#15]
When I used C-style arrays of doubles, which were allocated on the heap within the constructor of the VClamp class, which derives from the Model class, and freed those arrays with ```delete[]``` in the descructor ```VClamp::~VClamp``` I observed uncontrolled crashes (no error code) of stdpc.
When trying to debug, I put a console output into that constructor and it looks as if it is called twice (even though I was unable to establish whether potentially the calls were from different objects of the class). 
For now I am using ```std::vector``` class members instead and ```vector::resize()``` to allocate the necessary space and everything works; however, I wonder whether the observed behaviour is as intended.

**Comment by kernfel** [comment]
I'm closing this, since we've got both a workaround (use vectors) and a new release since. There's a chance that I'll get around to improving the mess I've made with model classes, which this issue may be related to, at some point in the future...
