### ISSUE TITLE
Make a release, including ready-to-go binaries?

### ISSUE THREAD

**Issue by tnowotny** [tnowotny/stdpc#4]
@kernfel , should we include fully compiled binaries into the version control and then make a release?
Or what do you think is the best way to make binaries available?

**Comment by tnowotny** [comment]
I suppose we could make a homepage at github.io and provide binaries there? Does this make sense?

**Comment by kernfel** [comment]
Yes, I'd do much the same I've done for the release candidates. I could (.. should) probably do the newer Digidata driver/s before doing a full release though. Are you pressed for time regarding submissions on NITRC or elsewhere, or could I spend a couple of days writing/testing on the Digidata testbeds next week?

**Comment by kernfel** [comment]
Sorry, that was in reply to the first post. Do you think it's worth making an .io page? I find the Release feature we've got here handy enough, we just need to point to it from the Readme.

Speaking of which, documentation is also outstanding.

**Comment by tnowotny** [comment]
I don't think we're pressed for time. Just picking things up again after Xmas break.
Where did you  deposit binaries previously?

**Comment by kernfel** [comment]
Along with the releases, [here](https://github.com/tnowotny/stdpc/releases).

**Comment by tnowotny** [comment]
Oh, I see, didn't realize that you can add files to these; I guess I am being a bit daft in public here - oh well.
Yes, this is perfectly fine if we link to it in the appropriate places. So, don't mind me and carry on.

**Comment by kernfel** [comment]
Done. Cue the inevitable "Aaah, I've found a terrible bug!" in five minutes.
