### ISSUE TITLE
Yuelin Shi problems with script files

### ISSUE THREAD

**Issue by tnowotny** [tnowotny/stdpc#5]
Apparently, when 
```is >> dblval;```
reads the last number from an ASCII file right at the file's end, 
```is.good();```
subsequently returns ```false```, even when the number was read successfully. 
This is what caused the confusion. I guess we need to start testing for end-of-file more explicitly instead of using is.good() after a failed read to indicate the end.

**Comment by kernfel** [comment]
Fixed by #3.
